### ISSUE TITLE
Don't assume builting top-level accounts

### ISSUE THREAD

**Issue by tbm** [LaunchPlatform/beancount-parser#1]
account.lark has:

```
BUILTIN_ACCOUNTS: "Assets" | "Liabilities" | "Equity" | "Income" | "Expenses"
...
ACCOUNT: BUILTIN_ACCOUNTS [":" ACCOUNT_COMPONENT]*
```

The top-level accounts can actually be configured using options (e.g. `option "name_assets" "Aktiva"`), so I don't think the parser should assume the default (builtin) top-level accounts.

**Comment by fangpenlin** [comment]
That's a good point. Thanks for letting me know. Didn't know that you can have different account name other than the built-in ones, will address that shortly
