### ISSUE TITLE
Account names require sub-accounts

### ISSUE THREAD

**Issue by tbm** [LaunchPlatform/beancount-parser#2]
Account names require a sub-name.  Just a top-level account on its own (e.g. `Income`) is not valid.  You need a sub-account (e.g. `Income:Foo`).

test_account.py has `Assets`, `Expenses`, `Income` and `Foobar` as valid but they are all invalid.

Example:

```
2010-10-01 open Income:Foo
2010-10-01 open Income

2022-04-02 * "Bar"
    Income        10.00
    Income:Foo
```

```
/home/tbm/Downloads/d:3:       Invalid token: 'Income'

/home/tbm/Downloads/d:6:       Invalid token: 'Income'
```

**Comment by fangpenlin** [comment]
Looks like the line

```
Income        10.00
```

is missing currency? Try making it

```
Income        10.00 USD
```

or is currency actually optional for posting?

**Comment by tbm** [comment]
Sorry, the currency is missing, but if you add it you will see it still complains about `Income`.  `Income` is not a valid account name.  It needs a sub-account: `Income:Something`.

Amounts without currency are *not* valid in beancount (they are in ledger).  This was just a bug in my example.
