### ISSUE TITLE
Does not handle expressions in balance assertions

### ISSUE THREAD

**Issue by ambroisie** [LaunchPlatform/beancount-parser#5]
The following line throws an unexpected input error:

```beancount
2000-01-01 balance Assets:Example (10.00 - 0.01) EUR
```

```
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: No terminal matches '(' in the current parser context, at line 1 col 35

2000-01-01 balance Assets:Example (10.00 - 0.01) EUR
                                  ^
Expected one of: 
        * SIGNED_NUMBER

Previous tokens: Token('ACCOUNT', 'Assets:Example')
```

**Comment by ambroisie** [comment]
A cursory glance at the grammar shows that the `amount` rule should instead accept math expressions, as can be seen [upstream](https://github.com/beancount/beancount/blob/84cb9f63be8024a53d0b7ca66aa5900e0a538d1f/beancount/cparser/parser.yxx#L1032)

**Comment by fangpenlin** [comment]
That's correct, for now the amount rule doesn't handle match expression.

I am still thinking whether to support that syntax. The main goal of this parser lib for now is to support beancount-black, the formatter. Math expression makes it harder to format. Personally, I think the math expression brings unnecessary complexity to the system. The math expression seems to be trading convenience of writing vs reading. Take `10.00 - 0.01`, now when I read it I need to calculate it in mind to understand that's `9.99`. Yes, that's extra step when you write the entry, but that's only done once, you could be reading the same line maybe 10 times more easily down the road. The calculation could be done from the editor end, such as a VIM plugin or VSCode plugin, or BeanHub.io will do that for you in the future, and only the end result is written into the file. In this way you get both readability of the book and also easy to write.

With that in mind, I must say I don't agree 100% of all the syntax beancount currently supports, or going to support. In the end I think I will need to make it clear that the beancount-parser will only support a subset of official beancount syntax for now. It's not meant to be a replacement of beancount core lib after all.

Anyway, I will leave this issue open and think about it, I will also update the readme to make it very clear that this library only supports a subset of beancount syntax, and may not support all of them.

**Comment by ambroisie** [comment]
> The math expression seems to be trading convenience of writing vs reading. Take 10.00 - 0.01, now when I read it I need to calculate it in mind to understand that's 9.99.

I would argue the exact opposite, I don't use math expressions to save mental math but to stick to actual documents : one of my monthly transactions is in another currency, and has an added cost due to paying in dollars. My bank statement regularly has the transaction included on one month, but the extra cost on another : for ease of matching my bank statement to my ledger, I "adjust" the balance to match what is written on my statement, while not having to split that transaction in time to account for my bank delaying a part of its payment.

**Comment by fangpenlin** [comment]
I see, interesting. Yeah, if that's for documentation purpose, I see why it's useful.  okay, I will find a time to add that support, thanks for the feedbacks 👍

**Comment by fangpenlin** [comment]
close by #12
